Fix zero-division errors in pulse generation functions
Fixed ZeroDivisionError in three functions:
- generate_phase_coded_pulse: samples_per_chip can be zero
- generate_freq_coded_pulse: samples_per_hop can be zero
- generate_lfm_chirp: chirp_samples can be zero

All now use max(1, int(...)) to ensure minimum value of 1.

Error was:
ZeroDivisionError: division by zero
at signal_generator.py:228 in generate_phase_coded_pulse
n_repeats = int(np.ceil(n_samples / len(phase_code)))

This occurred when symbol_rate caused very small durations,
resulting in zero samples per chip/hop/chirp.